# Generated by Django 3.2.6 on 2021-08-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('Profile_image', models.ImageField(upload_to='images/')),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Short_description', models.TextField(max_length=200)),
                ('Long_description', models.TextField(max_length=1000)),
                ('Degree', models.IntegerField()),
                ('Year_of_passing', models.IntegerField()),
                ('Certificate_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
